/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.8.10"

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    id("com.github.ben-manes.versions") version "0.51.0"
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

java {
    // see: https://docs.gradle.org/6.8.3/release-notes.html
    consistentResolution {
        useCompileClasspathVersions()
    }
    //sourceCompatibility = JavaVersion.VERSION_1_8
    // targetCompatibility = JavaVersion.VERSION_1_8
}

application {

    // Define the main class for shadowJar task
    val mainClassName = "com.example.CliKt"
    // Define the main class for the application plugin
    mainClass.set(mainClassName)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    implementation(platform("com.azure:azure-sdk-bom:1.2.20"))
    implementation("com.azure:azure-messaging-eventhubs")
    implementation("com.azure:azure-identity")
    //implementation("com.azure:azure-sdk-bom:1.2.20")
    //implementation("com.azure:azure-messaging-eventhubs:5.18.1")
    //implementation("com.azure:azure-identity:1.11.2")


    implementation("com.github.ajalt.clikt:clikt:4.2.2")
    implementation("io.github.microutils:kotlin-logging-jvm:3.0.5")
    //implementation("ch.qos.logback:logback-classic:1.5.0")
}



tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks {

    withType<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar> {
        mergeServiceFiles()
    }
}
